
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Stack;
import org.mariuszgromada.math.mxparser.*;

/*
 * Scientific Calculator
 * Capable of doing basic scientific calculations.
 * Developed with Java Swing and mXparser library.
 */
/**
 *
 * @author Robin Rezwan | http://github.com/robinrezwan
 */
public class ScientificCalculator extends javax.swing.JFrame {

    String mode = "DEG";
    boolean shift = false;

    String expression = "";
    Stack<String> inputStack = new Stack<>();
    String result = "";
    String ans = "";

    /**
     * Creates new form ScientificCalculator
     */
    public ScientificCalculator() {
        mXparser.setDegreesMode();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        buttonShift = new javax.swing.JButton();
        buttonFactorial = new javax.swing.JButton();
        buttonOpeningBracket = new javax.swing.JButton();
        buttonClosingBracket = new javax.swing.JButton();
        buttonMode = new javax.swing.JButton();
        buttonPercent = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonPower = new javax.swing.JButton();
        buttonRoot = new javax.swing.JButton();
        buttonLog = new javax.swing.JButton();
        buttonLn = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        buttonAC = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        buttonE = new javax.swing.JButton();
        buttonPi = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonDEL = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonDot = new javax.swing.JButton();
        buttonEXP = new javax.swing.JButton();
        buttonAns = new javax.swing.JButton();
        buttonEqual = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        secondaryDisplay = new javax.swing.JTextField();
        primaryDisplay = new javax.swing.JTextField();
        degLabel = new javax.swing.JLabel();
        radLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(248, 248, 248));

        buttonPanel.setBackground(new java.awt.Color(248, 248, 248));

        buttonShift.setBackground(new java.awt.Color(102, 102, 102));
        buttonShift.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonShift.setForeground(new java.awt.Color(255, 255, 255));
        buttonShift.setText("Shift");
        buttonShift.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShiftActionPerformed(evt);
            }
        });

        buttonFactorial.setBackground(new java.awt.Color(175, 175, 175));
        buttonFactorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonFactorial.setText("!");
        buttonFactorial.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFactorialActionPerformed(evt);
            }
        });

        buttonOpeningBracket.setBackground(new java.awt.Color(175, 175, 175));
        buttonOpeningBracket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonOpeningBracket.setText("(");
        buttonOpeningBracket.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonOpeningBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpeningBracketActionPerformed(evt);
            }
        });

        buttonClosingBracket.setBackground(new java.awt.Color(175, 175, 175));
        buttonClosingBracket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonClosingBracket.setText(")");
        buttonClosingBracket.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonClosingBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClosingBracketActionPerformed(evt);
            }
        });

        buttonMode.setBackground(new java.awt.Color(194, 51, 64));
        buttonMode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMode.setForeground(new java.awt.Color(255, 255, 255));
        buttonMode.setText("Deg/Rad");
        buttonMode.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModeActionPerformed(evt);
            }
        });

        buttonPercent.setBackground(new java.awt.Color(175, 175, 175));
        buttonPercent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPercent.setText("%");
        buttonPercent.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPercentActionPerformed(evt);
            }
        });

        buttonDivide.setBackground(new java.awt.Color(175, 175, 175));
        buttonDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDivide.setText("÷");
        buttonDivide.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonPower.setBackground(new java.awt.Color(175, 175, 175));
        buttonPower.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPower.setText("^");
        buttonPower.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowerActionPerformed(evt);
            }
        });

        buttonRoot.setBackground(new java.awt.Color(175, 175, 175));
        buttonRoot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonRoot.setText("√");
        buttonRoot.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRootActionPerformed(evt);
            }
        });

        buttonLog.setBackground(new java.awt.Color(175, 175, 175));
        buttonLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLog.setText("log");
        buttonLog.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });

        buttonLn.setBackground(new java.awt.Color(175, 175, 175));
        buttonLn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLn.setText("ln");
        buttonLn.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLnActionPerformed(evt);
            }
        });

        buttonSin.setBackground(new java.awt.Color(175, 175, 175));
        buttonSin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSin.setText("sin");
        buttonSin.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonCos.setBackground(new java.awt.Color(175, 175, 175));
        buttonCos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCos.setText("cos");
        buttonCos.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        buttonTan.setBackground(new java.awt.Color(175, 175, 175));
        buttonTan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTan.setText("tan");
        buttonTan.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTanActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(245, 245, 245));
        button8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button8.setText("8");
        button8.setPreferredSize(new java.awt.Dimension(100, 20));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(245, 245, 245));
        button4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button4.setText("4");
        button4.setPreferredSize(new java.awt.Dimension(100, 20));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        buttonAC.setBackground(new java.awt.Color(251, 167, 85));
        buttonAC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAC.setText("AC");
        buttonAC.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonACActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(245, 245, 245));
        button7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button7.setText("7");
        button7.setPreferredSize(new java.awt.Dimension(100, 20));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(245, 245, 245));
        button5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button5.setText("5");
        button5.setPreferredSize(new java.awt.Dimension(100, 20));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        buttonE.setBackground(new java.awt.Color(175, 175, 175));
        buttonE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonE.setText("e");
        buttonE.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEActionPerformed(evt);
            }
        });

        buttonPi.setBackground(new java.awt.Color(175, 175, 175));
        buttonPi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPi.setText("π");
        buttonPi.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPiActionPerformed(evt);
            }
        });

        buttonMultiply.setBackground(new java.awt.Color(175, 175, 175));
        buttonMultiply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMultiply.setText("×");
        buttonMultiply.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonDEL.setBackground(new java.awt.Color(251, 167, 85));
        buttonDEL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDEL.setText("DEL");
        buttonDEL.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDELActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(245, 245, 245));
        button6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button6.setText("6");
        button6.setPreferredSize(new java.awt.Dimension(100, 20));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(245, 245, 245));
        button9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button9.setText("9");
        button9.setPreferredSize(new java.awt.Dimension(100, 20));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(245, 245, 245));
        button1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button1.setText("1");
        button1.setPreferredSize(new java.awt.Dimension(100, 20));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(245, 245, 245));
        button2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button2.setText("2");
        button2.setPreferredSize(new java.awt.Dimension(100, 20));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(245, 245, 245));
        button3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button3.setText("3");
        button3.setPreferredSize(new java.awt.Dimension(100, 20));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonPlus.setBackground(new java.awt.Color(175, 175, 175));
        buttonPlus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonPlus.setText("+");
        buttonPlus.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlusActionPerformed(evt);
            }
        });

        buttonMinus.setBackground(new java.awt.Color(175, 175, 175));
        buttonMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMinus.setText("-");
        buttonMinus.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusActionPerformed(evt);
            }
        });

        button0.setBackground(new java.awt.Color(245, 245, 245));
        button0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button0.setText("0");
        button0.setPreferredSize(new java.awt.Dimension(100, 20));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonDot.setBackground(new java.awt.Color(245, 245, 245));
        buttonDot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDot.setText(".");
        buttonDot.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDotActionPerformed(evt);
            }
        });

        buttonEXP.setBackground(new java.awt.Color(175, 175, 175));
        buttonEXP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonEXP.setText("EXP");
        buttonEXP.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEXPActionPerformed(evt);
            }
        });

        buttonAns.setBackground(new java.awt.Color(175, 175, 175));
        buttonAns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAns.setText("Ans");
        buttonAns.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnsActionPerformed(evt);
            }
        });

        buttonEqual.setBackground(new java.awt.Color(40, 110, 220));
        buttonEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonEqual.setForeground(new java.awt.Color(255, 255, 255));
        buttonEqual.setText("=");
        buttonEqual.setPreferredSize(new java.awt.Dimension(100, 20));
        buttonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonOpeningBracket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonClosingBracket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonPi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonEXP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonShift, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpeningBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClosingBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPower, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEXP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAns, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        displayPanel.setBackground(new java.awt.Color(248, 248, 248));

        secondaryDisplay.setEditable(false);
        secondaryDisplay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        secondaryDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        primaryDisplay.setEditable(false);
        primaryDisplay.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        primaryDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        degLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        degLabel.setText("DEG");

        radLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        radLabel.setForeground(new java.awt.Color(192, 192, 192));
        radLabel.setText("RAD");

        titleLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setText("Scientific Calculator");

        shiftLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        shiftLabel.setForeground(new java.awt.Color(192, 192, 192));
        shiftLabel.setText("SHIFT");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondaryDisplay)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addComponent(degLabel)
                        .addGap(8, 8, 8)
                        .addComponent(radLabel)
                        .addGap(8, 8, 8)
                        .addComponent(shiftLabel)
                        .addGap(268, 268, 268)
                        .addComponent(titleLabel))
                    .addComponent(primaryDisplay, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degLabel)
                    .addComponent(radLabel)
                    .addComponent(titleLabel)
                    .addComponent(shiftLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondaryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primaryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShiftActionPerformed
        // TODO add your handling code here:
        if (shift) {
            shift = false;
            shiftLabel.setForeground(Color.LIGHT_GRAY);

            buttonSin.setText("sin");
            buttonCos.setText("cos");
            buttonTan.setText("tan");
            buttonLn.setText("ln");
            buttonLog.setText("log");
            buttonRoot.setText("√");
        } else {
            shift = true;
            shiftLabel.setForeground(Color.BLACK);

            buttonSin.setText("sin⁻¹");
            buttonCos.setText("cos⁻¹");
            buttonTan.setText("tan⁻¹");
            buttonLn.setText("eˣ");
            buttonLog.setText("10ˣ");
            buttonRoot.setText("x²");
        }
    }//GEN-LAST:event_buttonShiftActionPerformed

    private void buttonPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPercentActionPerformed
        // TODO add your handling code here:
        inputStack.push("%");
        expression += "%";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonPercentActionPerformed

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEActionPerformed
        // TODO add your handling code here:
        inputStack.push("e");
        expression += "e";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonEActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        inputStack.push("7");
        expression += "7";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button7ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        inputStack.push("4");
        expression += "4";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        inputStack.push("2");
        expression += "2";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        inputStack.push("1");
        expression += "1";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button1ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        inputStack.push("0");
        expression += "0";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlusActionPerformed
        // TODO add your handling code here:
        inputStack.push("+");
        expression += "+";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonPlusActionPerformed

    private void buttonEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEXPActionPerformed
        // TODO add your handling code here:
        inputStack.push("E");
        expression += "E";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonEXPActionPerformed

    private void buttonDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDELActionPerformed
        // TODO add your handling code here:
        if (!inputStack.empty()) {
            inputStack.pop();

            Object inputStackArray[] = inputStack.toArray();

            expression = "";

            for (int i = 0; i < inputStackArray.length; i++) {
                expression += inputStackArray[i];
            }

            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonDELActionPerformed

    private void buttonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPiActionPerformed
        // TODO add your handling code here:
        inputStack.push("π");
        expression += "π";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonPiActionPerformed

    private void buttonFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFactorialActionPerformed
        // TODO add your handling code here:
        inputStack.push("!");
        expression += "!";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonFactorialActionPerformed

    private void buttonClosingBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClosingBracketActionPerformed
        // TODO add your handling code here:
        inputStack.push(")");
        expression += ")";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonClosingBracketActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        inputStack.push("3");
        expression += "3";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button3ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        inputStack.push("5");
        expression += "5";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        inputStack.push("6");
        expression += "6";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button6ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        inputStack.push("8");
        expression += "8";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        inputStack.push("9");
        expression += "9";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_button9ActionPerformed

    private void buttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinusActionPerformed
        // TODO add your handling code here:
        inputStack.push("-");
        expression += "-";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonMinusActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        // TODO add your handling code here:
        inputStack.push("×");
        expression += "×";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        // TODO add your handling code here:
        inputStack.push("÷");
        expression += "÷";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDotActionPerformed
        // TODO add your handling code here:
        inputStack.push(".");
        expression += ".";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonDotActionPerformed

    private void buttonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonACActionPerformed
        // TODO add your handling code here:
        inputStack.clear();
        expression = "";
        primaryDisplay.setText(expression);
        secondaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonACActionPerformed

    private void buttonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualActionPerformed
        // TODO add your handling code here:
        if (expression.length() != 0) {
            try {
                String tempExpression = expression.replace("×", "*");
                tempExpression = tempExpression.replace("÷", "/");
                tempExpression = tempExpression.replace("log", "log10");
                tempExpression = tempExpression.replace("π", "pi");
                tempExpression = tempExpression.replace("e", "e");
                tempExpression = tempExpression.replace("√", "sqrt");
                tempExpression = tempExpression.replace("EXP", "*10^");
                tempExpression = tempExpression.replace("sin⁻¹", "arcsin");
                tempExpression = tempExpression.replace("cos⁻¹", "arccos");
                tempExpression = tempExpression.replace("tan⁻¹", "arctan");

                while (tempExpression.contains("%")) {
                    if ((tempExpression.indexOf("%") >= tempExpression.length() - 1)
                            || !Character.isDigit(tempExpression.charAt(tempExpression.indexOf("%") + 1))) {
                        tempExpression = tempExpression.replaceFirst("%", "/100");
                    } else {
                        throw new Exception("Error");
                    }
                }

                // Expression evaluation with mXparser
                Argument Ans = new Argument("Ans", ans);
                Expression exp = new Expression(tempExpression, Ans);

                double value = exp.calculate();

                if (Double.isNaN(value)) {
                    throw new Exception("Error");
                }

                // Format the result for showing on display
                DecimalFormat decimalFormat = new DecimalFormat("0.#########");
                result = decimalFormat.format(value);

            } catch (Exception e) {
                result = "Error";
            }

            primaryDisplay.setText(result);
            secondaryDisplay.setText(expression + " =");

            inputStack.clear();
            expression = "";

            if (!result.equals("Error")) {
                ans = result;
                inputStack.push(result);
                expression = result;
            }
        }
    }//GEN-LAST:event_buttonEqualActionPerformed

    private void buttonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowerActionPerformed
        // TODO add your handling code here:
        inputStack.push("^");
        expression += "^";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonPowerActionPerformed

    private void buttonOpeningBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpeningBracketActionPerformed
        // TODO add your handling code here:
        inputStack.push("(");
        expression += "(";
        primaryDisplay.setText(expression);
    }//GEN-LAST:event_buttonOpeningBracketActionPerformed

    private void buttonRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRootActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("^2");
            expression += "^2";
            primaryDisplay.setText(expression);

            shift = false;
        } else {
            inputStack.push("√(");
            expression += "√(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonRootActionPerformed

    private void buttonAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnsActionPerformed
        // TODO add your handling code here:
        if (ans.length() != 0) {

            inputStack.push("Ans");
            expression += "Ans";

            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonAnsActionPerformed

    private void buttonModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModeActionPerformed
        // TODO add your handling code here:
        if (mode.equals("DEG")) {
            mXparser.setRadiansMode();

            mode = "RAD";
            radLabel.setForeground(Color.BLACK);
            degLabel.setForeground(Color.LIGHT_GRAY);
        } else if (mode.equals("RAD")) {
            mXparser.setDegreesMode();

            mode = "DEG";
            degLabel.setForeground(Color.BLACK);
            radLabel.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_buttonModeActionPerformed

    private void buttonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSinActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("sin⁻¹(");
            expression += "sin⁻¹(";
            primaryDisplay.setText(expression);
        } else {
            inputStack.push("sin(");
            expression += "sin(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonSinActionPerformed

    private void buttonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCosActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("cos⁻¹(");
            expression += "cos⁻¹(";
            primaryDisplay.setText(expression);
        } else {
            inputStack.push("cos(");
            expression += "cos(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonCosActionPerformed

    private void buttonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTanActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("tan⁻¹(");
            expression += "tan⁻¹(";
            primaryDisplay.setText(expression);
        } else {
            inputStack.push("tan(");
            expression += "tan(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonTanActionPerformed

    private void buttonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("10^");
            expression += "10^";
            primaryDisplay.setText(expression);
        } else {
            inputStack.push("log(");
            expression += "log(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonLogActionPerformed

    private void buttonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLnActionPerformed
        // TODO add your handling code here:
        if (shift) {
            inputStack.push("e^");
            expression += "e^";
            primaryDisplay.setText(expression);
        } else {
            inputStack.push("ln(");
            expression += "ln(";
            primaryDisplay.setText(expression);
        }
    }//GEN-LAST:event_buttonLnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ScientificCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAC;
    private javax.swing.JButton buttonAns;
    private javax.swing.JButton buttonClosingBracket;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonDEL;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonDot;
    private javax.swing.JButton buttonE;
    private javax.swing.JButton buttonEXP;
    private javax.swing.JButton buttonEqual;
    private javax.swing.JButton buttonFactorial;
    private javax.swing.JButton buttonLn;
    private javax.swing.JButton buttonLog;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonMode;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonOpeningBracket;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton buttonPercent;
    private javax.swing.JButton buttonPi;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPower;
    private javax.swing.JButton buttonRoot;
    private javax.swing.JButton buttonShift;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonTan;
    private javax.swing.JLabel degLabel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField primaryDisplay;
    private javax.swing.JLabel radLabel;
    private javax.swing.JTextField secondaryDisplay;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
